<?php

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('orders')->delete();

        \DB::table('orders')->insert(array(
            0 =>
            array(
                'user_id' => 2,
                'id' => 1,
                'charge_id' => NULL,
                'receiver_name' => 'hm',
                'receiver_mobile' => 5484,
                'receiver_address' => 'vsvd',
                'civil_id' => 5784,
                'country' => 'sa',
                'amount' => '2.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'pending',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-03-08 07:37:12',
                'updated_at' => '2019-03-08 07:37:12',
            ),
            1 =>
            array(
                'user_id' => 2,
                'id' => 2,
                'charge_id' => NULL,
                'receiver_name' => 'jk',
                'receiver_mobile' => 5457,
                'receiver_address' => 'dhdhs',
                'civil_id' => 8484,
                'country' => 'qatar',
                'amount' => '8.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'pending',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-03-08 07:38:49',
                'updated_at' => '2019-03-08 07:38:49',
            ),
            2 =>
            array(
                'user_id' => 2,
                'id' => 3,
                'charge_id' => 'chg_c5R41320191113h9F40803213',
                'receiver_name' => 'tm',
                'receiver_mobile' => 5484,
                'receiver_address' => 'hsvs',
                'civil_id' => 2484,
                'country' => 'qatar',
                'amount' => '5.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => 1,
                'status' => 'pending',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-03-08 07:40:50',
                'updated_at' => '2019-03-08 08:12:02',
            ),
            3 =>
            array(
                'user_id' => 2,
                'id' => 4,
                'charge_id' => 'chg_u2B52920191114a9LK0803042',
                'receiver_name' => 'tm2',
                'receiver_mobile' => 5484,
                'receiver_address' => 'hsvs',
                'civil_id' => 2484,
                'country' => 'qatar',
                'amount' => '5.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => 1,
                'status' => 'pending',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-03-08 08:13:08',
                'updated_at' => '2019-03-08 08:13:17',
            ),
            4 =>
            array(
                'user_id' => 2,
                'id' => 5,
                'charge_id' => 'chg_Lo2c3520191115c9DR0803457',
                'receiver_name' => 'hj',
                'receiver_mobile' => 5484,
                'receiver_address' => 'bdbd',
                'civil_id' => 5484,
                'country' => 'qatar',
                'amount' => '5.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'pending',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-03-08 08:14:14',
                'updated_at' => '2019-03-08 08:14:24',
            ),
            5 =>
            array(
                'user_id' => 2,
                'id' => 6,
                'charge_id' => 'chg_j5JL3020191116He940803986',
                'receiver_name' => 'uj',
                'receiver_mobile' => 545,
                'receiver_address' => 'vsv',
                'civil_id' => 548,
                'country' => 'bahrain',
                'amount' => '7.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'pending',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-03-08 08:15:10',
                'updated_at' => '2019-03-08 08:15:18',
            ),
            6 =>
            array(
                'user_id' => 2,
                'id' => 7,
                'charge_id' => 'chg_j4K93520191118y4PQ0803518',
                'receiver_name' => 'tm22',
                'receiver_mobile' => 5484,
                'receiver_address' => 'hsvs',
                'civil_id' => 2484,
                'country' => 'qatar',
                'amount' => '5.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'success',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-03-08 08:17:15',
                'updated_at' => '2019-03-08 08:19:13',
            ),
            7 =>
            array(
                'user_id' => 2,
                'id' => 8,
                'charge_id' => 'chg_Rj4g1120191130Xm450803352',
                'receiver_name' => 'tm25',
                'receiver_mobile' => 5484,
                'receiver_address' => 'hsvs',
                'civil_id' => 2484,
                'country' => 'qatar',
                'amount' => '5.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'failed',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-03-08 08:28:50',
                'updated_at' => '2019-03-08 08:32:53',
            ),
            8 =>
            array(
                'user_id' => 2,
                'id' => 9,
                'charge_id' => 'chg_Qh294620191419n5KL1304659',
                'receiver_name' => 'jo',
                'receiver_mobile' => 5484,
                'receiver_address' => 'hshs',
                'civil_id' => 5484,
                'country' => 'bahrain',
                'amount' => '2.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'failed',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-13 11:18:54',
                'updated_at' => '2019-04-13 11:20:31',
            ),
            9 =>
            array(
                'user_id' => 2,
                'id' => 10,
                'charge_id' => 'chg_Rp5w0020191422Ri991304333',
                'receiver_name' => 'cv',
                'receiver_mobile' => 5154,
                'receiver_address' => 'bs',
                'civil_id' => 8484,
                'country' => 'qatar',
                'amount' => '21.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'failed',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-13 11:21:08',
                'updated_at' => '2019-04-13 11:21:59',
            ),
            10 =>
            array(
                'user_id' => 2,
                'id' => 11,
                'charge_id' => 'chg_Fb523020191423a4J51304726',
                'receiver_name' => 'hj',
                'receiver_mobile' => 54,
                'receiver_address' => 'bd',
                'civil_id' => 54,
                'country' => 'uae',
                'amount' => '3.00',
                'charges' => 5,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'failed',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-13 11:22:38',
                'updated_at' => '2019-04-13 11:23:42',
            ),
            11 =>
            array(
                'user_id' => 2,
                'id' => 12,
                'charge_id' => 'chg_Jx450520191425g4L41304438',
                'receiver_name' => 'hshs',
                'receiver_mobile' => 5484,
                'receiver_address' => 'bs',
                'civil_id' => 840,
                'country' => 'qatar',
                'amount' => '2.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'failed',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-13 11:24:13',
                'updated_at' => '2019-04-13 11:25:35',
            ),
            12 =>
            array(
                'user_id' => 2,
                'id' => 13,
                'charge_id' => 'chg_Du2y2420191431Tp4h1304733',
                'receiver_name' => 'hs',
                'receiver_mobile' => 848,
                'receiver_address' => 'hs',
                'civil_id' => 878,
                'country' => 'oman',
                'amount' => '1.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'failed',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-13 11:30:32',
                'updated_at' => '2019-04-13 11:31:17',
            ),
            13 =>
            array(
                'user_id' => 2,
                'id' => 14,
                'charge_id' => 'chg_q2PB0020191433m9ZQ1304823',
                'receiver_name' => 'io',
                'receiver_mobile' => 54,
                'receiver_address' => 'bs',
                'civil_id' => 54,
                'country' => 'qatar',
                'amount' => '3.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'failed',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-13 11:32:08',
                'updated_at' => '2019-04-13 11:33:11',
            ),
            14 =>
            array(
                'user_id' => 2,
                'id' => 15,
                'charge_id' => 'chg_Je595320191434l2DZ1304185',
                'receiver_name' => 'yu',
                'receiver_mobile' => 54,
                'receiver_address' => 'dv',
                'civil_id' => 54,
                'country' => 'sa',
                'amount' => '3.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'failed',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-13 11:34:01',
                'updated_at' => '2019-04-13 11:34:55',
            ),
            15 =>
            array(
                'user_id' => 2,
                'id' => 16,
                'charge_id' => 'chg_q4Q50920191436Zj941304063',
                'receiver_name' => 'dhjd',
                'receiver_mobile' => 548,
                'receiver_address' => 'd',
                'civil_id' => 488,
                'country' => 'sa',
                'amount' => '1.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'failed',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-13 11:35:17',
                'updated_at' => '2019-04-13 11:35:55',
            ),
            16 =>
            array(
                'user_id' => 2,
                'id' => 17,
                'charge_id' => 'chg_Kw525520190819Pa5l1404584',
                'receiver_name' => 'Hj',
                'receiver_mobile' => 54,
                'receiver_address' => 'Shsh',
                'civil_id' => 48,
                'country' => 'uae',
                'amount' => '2.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'failed',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-14 05:19:02',
                'updated_at' => '2019-04-14 05:19:59',
            ),
            17 =>
            array(
                'user_id' => 2,
                'id' => 18,
                'charge_id' => 'chg_a9L55320190821Hy9e1404393',
                'receiver_name' => 'Op',
                'receiver_mobile' => 54,
                'receiver_address' => 'Jdhd',
                'civil_id' => 57,
                'country' => 'sa',
                'amount' => '6.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => 1,
                'status' => 'completed',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-14 05:21:00',
                'updated_at' => '2019-04-14 05:42:11',
            ),
            18 =>
            array(
                'user_id' => 2,
                'id' => 19,
                'charge_id' => NULL,
                'receiver_name' => 'Ko',
                'receiver_mobile' => 45,
                'receiver_address' => 'Sjs',
                'civil_id' => 45,
                'country' => 'bahrain',
                'amount' => '2.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'pending',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-14 06:45:40',
                'updated_at' => '2019-04-14 06:45:40',
            ),
            19 =>
            array(
                'user_id' => 2,
                'id' => 20,
                'charge_id' => NULL,
                'receiver_name' => 'Hg',
                'receiver_mobile' => 54,
                'receiver_address' => 'Hssu',
                'civil_id' => 4884,
                'country' => 'bahrain',
                'amount' => '3.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'pending',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-14 06:47:01',
                'updated_at' => '2019-04-14 06:47:01',
            ),
            20 =>
            array(
                'user_id' => 2,
                'id' => 21,
                'charge_id' => 'chg_e9P53220190959Ja9k1404455',
                'receiver_name' => 'Yu',
                'receiver_mobile' => 45,
                'receiver_address' => 'Ssj',
                'civil_id' => 84,
                'country' => 'bahrain',
                'amount' => '33.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'success',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-14 06:58:40',
                'updated_at' => '2019-04-14 07:00:22',
            ),
            21 =>
            array(
                'user_id' => 2,
                'id' => 22,
                'charge_id' => NULL,
                'receiver_name' => 'Po',
                'receiver_mobile' => 548,
                'receiver_address' => 'Uj',
                'civil_id' => 82,
                'country' => 'sa',
                'amount' => '7.00',
                'charges' => 5,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'pending',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-14 08:10:13',
                'updated_at' => '2019-04-14 08:10:13',
            ),
            22 =>
            array(
                'user_id' => 2,
                'id' => 23,
                'charge_id' => NULL,
                'receiver_name' => 'Jp',
                'receiver_mobile' => 544,
                'receiver_address' => 'Aa',
                'civil_id' => 5484,
                'country' => 'bahrain',
                'amount' => '4.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'pending',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-14 08:11:20',
                'updated_at' => '2019-04-14 08:11:20',
            ),
            23 =>
            array(
                'user_id' => 2,
                'id' => 24,
                'charge_id' => NULL,
                'receiver_name' => 'Fg',
                'receiver_mobile' => 54,
                'receiver_address' => 'Jk',
                'civil_id' => 787,
                'country' => 'qatar',
                'amount' => '1.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'pending',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-14 08:19:35',
                'updated_at' => '2019-04-14 08:19:35',
            ),
            24 =>
            array(
                'user_id' => 2,
                'id' => 25,
                'charge_id' => NULL,
                'receiver_name' => 'Cvh',
                'receiver_mobile' => 57,
                'receiver_address' => 'Asd',
                'civil_id' => 5487,
                'country' => 'sa',
                'amount' => '4.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'pending',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-14 08:21:11',
                'updated_at' => '2019-04-14 08:21:11',
            ),
            25 =>
            array(
                'user_id' => 2,
                'id' => 26,
                'charge_id' => 'chg_n4R92820191123Zj4c1404880',
                'receiver_name' => 'Kf',
                'receiver_mobile' => 67,
                'receiver_address' => 'Dj',
                'civil_id' => 64,
                'country' => 'qatar',
                'amount' => '6.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'success',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-14 08:22:36',
                'updated_at' => '2019-04-14 08:25:51',
            ),
            26 =>
            array(
                'user_id' => 2,
                'id' => 27,
                'charge_id' => NULL,
                'receiver_name' => 'Xc',
                'receiver_mobile' => 54,
                'receiver_address' => 'Hzhs',
                'civil_id' => 87,
                'country' => 'uae',
                'amount' => '6.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'pending',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-14 08:26:13',
                'updated_at' => '2019-04-14 08:26:13',
            ),
            27 =>
            array(
                'user_id' => 2,
                'id' => 28,
                'charge_id' => NULL,
                'receiver_name' => 'Hu',
                'receiver_mobile' => 5454,
                'receiver_address' => 'Udjd',
                'civil_id' => 484,
                'country' => 'qatar',
                'amount' => '9.00',
                'charges' => 5,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'pending',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-14 08:30:49',
                'updated_at' => '2019-04-14 08:30:49',
            ),
            28 =>
            array(
                'user_id' => 2,
                'id' => 29,
                'charge_id' => 'chg_Nk9u3220191133a2ZH1404090',
                'receiver_name' => 'Dd',
                'receiver_mobile' => 54,
                'receiver_address' => 'Djd',
                'civil_id' => 5424,
                'country' => 'qatar',
                'amount' => '3.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'success',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-14 08:32:39',
                'updated_at' => '2019-04-14 08:33:35',
            ),
            29 =>
            array(
                'user_id' => 2,
                'id' => 30,
                'charge_id' => NULL,
                'receiver_name' => 'Hdhd',
                'receiver_mobile' => 8484,
                'receiver_address' => 'Hxbx',
                'civil_id' => 5454,
                'country' => 'qatar',
                'amount' => '2.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'pending',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-14 08:33:56',
                'updated_at' => '2019-04-14 08:33:56',
            ),
            30 =>
            array(
                'user_id' => 2,
                'id' => 31,
                'charge_id' => 'chg_y5K43420191135n9T21404338',
                'receiver_name' => 'Idd',
                'receiver_mobile' => 5448,
                'receiver_address' => 'On',
                'civil_id' => 574,
                'country' => 'uae',
                'amount' => '2.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'success',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-14 08:34:41',
                'updated_at' => '2019-04-14 08:35:18',
            ),
            31 =>
            array(
                'user_id' => 2,
                'id' => 32,
                'charge_id' => 'chg_p9L43820190916i5LJ1604680',
                'receiver_name' => 'tm',
                'receiver_mobile' => 54,
                'receiver_address' => 'bdbs',
                'civil_id' => 548,
                'country' => 'bahrain',
                'amount' => '2.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => 9099,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'success',
                'location_data' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => '2019-04-16 06:15:44',
                'updated_at' => '2019-04-16 08:11:40',
            ),
            32 =>
            array(
                'user_id' => 2,
                'id' => 33,
                'charge_id' => 'chg_c9MP3920192145b5P91305280',
                'receiver_name' => 'jd',
                'receiver_mobile' => 548,
                'receiver_address' => 'bdb',
                'civil_id' => 844,
                'country' => NULL,
                'amount' => '2.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'failed',
                'location_data' => 'Kipco Tower, Kuwait City, Kuwait',
                'latitude' => '29.3757397',
                'longitude' => '47.9868396',
                'created_at' => '2019-05-13 18:44:38',
                'updated_at' => '2019-05-13 18:45:35',
            ),
            33 =>
            array(
                'user_id' => 2,
                'id' => 34,
                'charge_id' => 'chg_Ym493920191521e9D41705743',
                'receiver_name' => 'test location',
                'receiver_mobile' => 8454,
                'receiver_address' => 'bssb',
                'civil_id' => 5454,
                'country' => NULL,
                'amount' => '2.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'success',
                'location_data' => 'Kipco Tower, Kuwait City, Kuwait',
                'latitude' => '29.3757397',
                'longitude' => '47.9868396',
                'created_at' => '2019-05-17 12:20:40',
                'updated_at' => '2019-05-17 12:22:02',
            ),
            34 =>
            array(
                'user_id' => 2,
                'id' => 35,
                'charge_id' => 'chg_Fl994720191631b4M52505346',
                'receiver_name' => 'oul',
                'receiver_mobile' => 5484,
                'receiver_address' => 'svdv',
                'civil_id' => 5484,
                'country' => NULL,
                'amount' => '3.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'failed',
                'location_data' => NULL,
                'latitude' => '29.363466213179827',
                'longitude' => '47.99711762970753',
                'created_at' => '2019-05-25 13:30:26',
                'updated_at' => '2019-05-25 13:31:06',
            ),
            35 =>
            array(
                'user_id' => 2,
                'id' => 36,
                'charge_id' => 'chg_q4NP0620191634a9K22505295',
                'receiver_name' => 'pol',
                'receiver_mobile' => 545,
                'receiver_address' => 'bd',
                'civil_id' => 7578,
                'country' => NULL,
                'amount' => '3.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'success',
                'location_data' => NULL,
                'latitude' => '29.361101765469012',
                'longitude' => '47.99766022395937',
                'created_at' => '2019-05-25 13:32:46',
                'updated_at' => '2019-05-25 13:33:47',
            ),
            36 =>
            array(
                'user_id' => 2,
                'id' => 37,
                'charge_id' => 'chg_Oo9k2220191644x4L43105213',
                'receiver_name' => 'poi',
                'receiver_mobile' => 24848,
                'receiver_address' => 'bdbdhdhd',
                'civil_id' => 5448,
                'country' => NULL,
                'amount' => '1.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => NULL,
                'status' => 'success',
                'location_data' => NULL,
                'latitude' => '29.376204139529364',
                'longitude' => '47.987626886575335',
                'created_at' => '2019-05-31 13:42:55',
                'updated_at' => '2019-05-31 13:43:47',
            ),
            37 =>
            array(
                'user_id' => 2,
                'id' => 38,
                'charge_id' => 'chg_Dj5a1920191513Do4a0106914',
                'receiver_name' => 'udjd',
                'receiver_mobile' => 845440,
                'receiver_address' => 'dbbde',
                'civil_id' => 8484,
                'country' => NULL,
                'amount' => '1.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => 1,
                'status' => 'success',
                'location_data' => NULL,
                'latitude' => '29.10664853195474',
                'longitude' => '48.06101395664925',
                'created_at' => '2019-06-01 12:11:55',
                'updated_at' => '2019-06-01 12:12:43',
            ),
            38 =>
            array(
                'user_id' => 2,
                'id' => 39,
                'charge_id' => 'chg_a9B91420191756o2L90806556',
                'receiver_name' => 'tm3',
                'receiver_mobile' => 545,
                'receiver_address' => 'bdbd',
                'civil_id' => 5484,
                'country' => NULL,
                'amount' => '1.00',
                'charges' => 2,
                'order_type' => 'Cash',
                'code' => NULL,
                'converted_amount' => NULL,
                'saved' => 1,
                'status' => 'success',
                'location_data' => NULL,
                'latitude' => '29.076626512318523',
                'longitude' => '48.12956883373771',
                'created_at' => '2019-06-08 14:55:15',
                'updated_at' => '2019-06-08 14:56:20',
            ),
        ));
    }
}
